# Import Data From YFinance

In [ ]:
import yfinance
import numpy as np
from tensorflow import keras

In [ ]:
microsoft = yfinance.Ticker("MSFT")
data = microsoft.history()

y_train = data.Close
print(y_train)
x_train = np.arange(0, len(y_train))
print(x_train)


Date
2023-09-18 00:00:00-04:00    329.059998
2023-09-19 00:00:00-04:00    328.649994
2023-09-20 00:00:00-04:00    320.769989
2023-09-21 00:00:00-04:00    319.529999
2023-09-22 00:00:00-04:00    317.010010
2023-09-25 00:00:00-04:00    317.540009
2023-09-26 00:00:00-04:00    312.140015
2023-09-27 00:00:00-04:00    312.790009
2023-09-28 00:00:00-04:00    313.640015
2023-09-29 00:00:00-04:00    315.750000
2023-10-02 00:00:00-04:00    321.799988
2023-10-03 00:00:00-04:00    313.390015
2023-10-04 00:00:00-04:00    318.959991
2023-10-05 00:00:00-04:00    319.359985
2023-10-06 00:00:00-04:00    327.260010
2023-10-09 00:00:00-04:00    329.820007
2023-10-10 00:00:00-04:00    328.390015
2023-10-11 00:00:00-04:00    332.420013
2023-10-12 00:00:00-04:00    331.160004
2023-10-13 00:00:00-04:00    327.730011
2023-10-16 00:00:00-04:00    332.640015
2023-10-17 00:00:00-04:00    332.059998
Name: Close, dtype: float64
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


# Building Neural Network

In [ ]:
from keras.src.layers.serialization import activation

mlp = keras.Sequential([
    keras.layers.Input(shape = 1),
    keras.layers.Dense(200, activation="relu"),
    keras.layers.Dense(200, activation="relu"),
    keras.layers.Dense(200, activation="relu"),
    keras.layers.Dense(200, activation="relu"),
    keras.layers.Dense(1)
])

adamOptimizer = keras.optimizers.Adam()
mlp.compile(optimizer=adamOptimizer, loss="mean_squared_error")

mlp.fit(x_train, y_train, epochs = 5000, validation_split=.1)

mlp.predict([1])

Streaming output truncated to the last 5000 lines.
Epoch 2502/5000
1/1 [==============================] - 0s 70ms/step - loss: 5.1194 - val_loss: 165.3992
Epoch 2503/5000
1/1 [==============================] - 0s 58ms/step - loss: 5.1093 - val_loss: 166.9431
Epoch 2504/5000
1/1 [==============================] - 0s 79ms/step - loss: 5.1063 - val_loss: 169.9124
Epoch 2505/5000
1/1 [==============================] - 0s 75ms/step - loss: 5.1101 - val_loss: 163.2370
Epoch 2506/5000
1/1 [==============================] - 0s 78ms/step - loss: 5.1164 - val_loss: 172.1400
Epoch 2507/5000
1/1 [==============================] - 0s 54ms/step - loss: 5.1202 - val_loss: 162.3477
Epoch 2508/5000
1/1 [==============================] - 0s 80ms/step - loss: 5.1194 - val_loss: 171.2223
Epoch 2509/5000
1/1 [==============================] - 0s 77ms/step - loss: 5.1145 - val_loss: 164.3763
Epoch 2510/5000
1/1 [==============================] - 0s 88ms/step - loss: 5.1085 - val_loss: 168.2780
Epoch 2511/50

array([[328.2901]], dtype=float32)

In [ ]:
print(x_train[-1])

21


In [ ]:
mlp.predict([22])

1/1 [==============================] - 0s 37ms/step


array([[354.3751]], dtype=float32)